apiVersion: v1
kind: Service
metadata:
  name: bankassist-backend-service
  namespace: bankassist-ai
  labels:
    app.kubernetes.io/name: bankassist-backend
    app.kubernetes.io/part-of: bankassist-ai
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: bankassist-backend
