apiVersion: v1
kind: Secret
metadata:
  name: bankassist-secrets
  namespace: bankassist-ai
  labels:
    app.kubernetes.io/name: bankassist-backend
    app.kubernetes.io/part-of: bankassist-ai
type: Opaque
stringData:
  GROQ_API_KEY: "your_groq_api_key_here"
  PINECONE_API_KEY: "your_pinecone_api_key_here"
  JWT_SECRET_KEY: "bankassist_super_secret_jwt_key_enterprise_rag_2026_eks_production"
  MYSQL_ROOT_PASSWORD: "rootpassword"
  MYSQL_PASSWORD: "root"
